---
apiVersion: v1
kind: Service
metadata:
  name: mysql-otus
  labels:
    app: mysql-otus
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:
    app: mysql-otus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset-otus
spec:
  serviceName: "mysql-otus"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-otus
  template:
    metadata:
      labels:
        app: mysql-otus
    spec:
      containers:
        - name: mysql-otus
          image: mysql:latest
          ports:
            - containerPort: 3306
              name: mysqldb
          env:
            #- name: MYSQL_DATABASE
            #  value: myapp
            #- name: MYSQL_USER
            #  value: root
            - name: MYSQL_ROOT_PASSWORD
              value: masterkey
          volumeMounts:
            - name: mysqldb
              mountPath: /var/lib/mysql
              subPath: mysql
  volumeClaimTemplates:
    - metadata:
        name: mysqldb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi