apiVersion: v1
kind: ConfigMap
metadata:
  name: otus-config
data:
  # STORE_URI: root:masterkey@tcp(mysql-otus)/ # слеш нужен обязательно
  STORE_DB: otusdb
  GREETING: Bonjour
---
apiVersion: v1
kind: Secret
metadata:
  name: otus-secret
type: Opaque
data:
  STORE_URI: {{ printf "%s:%s@tcp(%s:%s)/"
    .Values.mysql.username
    .Values.mysql.rootPassword ( include "mysql.primary.fullname" .)
    .Values.mysql.service.port | b64enc | quote
  }}
